./opcode_pkg.sv
./alu_8.sv
./alu_opcode_logic.sv
./branch_logic.sv
./comparator_8.sv
./comparator_concatination.sv
./compare_flag_register_enable_logic.sv
./cpu8.sv
./cpu_memory_write_enable_logic.sv
./decoder_3.sv
./memory_array_256x8.sv
./mov_logic.sv
./mov_logic_register_module.sv
./mux_4to1.sv
./mux_8to1.sv
./program_counter.sv
./program_counter_adder.sv
./register_array_8.sv
./register_file_8.sv
./register_file_data_in_logic.sv
./register_file_read_write_logic.sv
./register_module.sv
